# frozen_string_literal: true

# BookingBriefJob generates an AI-powered pre-session brief for the mentor.
# Enqueued after a booking is confirmed. Uses the 'ai' queue for isolation.
#
# Architecture:
#   BookingService creates booking -> enqueues BookingBriefJob
#   Job calls LlmClient.generate_brief (OpenAI GPT-4o-mini)
#   Result stored in PreSessionBrief (content + token metrics)
#
# Idempotency: skips if PreSessionBrief already exists for the booking.
# Retry: 3 attempts with exponential backoff on LLM failures.
# Observability: logs model, tokens, latency for cost tracking.
#
# NOTE: Currently stubbed — generates placeholder brief without OpenAI.
# Set OPENAI_API_KEY in .env to enable real LLM generation.
class BookingBriefJob < ApplicationJob
  queue_as :ai
  sidekiq_options retry: 3

  def perform(booking_id)
    booking = Booking.includes(slot: { mentor: :mentor_profile }).find_by(id: booking_id)
    return unless booking&.confirmed?

    # Idempotency: skip if brief already generated
    return if PreSessionBrief.exists?(booking_id: booking_id)

    if ENV["OPENAI_API_KEY"].present?
      # Production path: call LlmClient (not yet implemented)
      generate_with_llm(booking)
    else
      # Stub path: generate placeholder brief for demonstration
      generate_stub_brief(booking)
    end
  end

  private

  def generate_stub_brief(booking)
    mentor = booking.slot.mentor
    member = booking.member

    content = <<~BRIEF
      ## Pre-Session Brief

      **Session:** #{member.name} with #{mentor.name}
      **Scheduled:** #{booking.slot.start_time.strftime("%B %d, %Y at %H:%M UTC")}

      ### Suggested Discussion Topics
      1. Career goals alignment with #{mentor.mentor_profile&.expertise&.first || "their"} expertise
      2. Current challenges and blockers
      3. Actionable next steps and accountability

      ### Preparation Notes
      - Review #{member.name}'s previous session notes (if any)
      - Prepare 2-3 open-ended questions to guide discussion
      - Have relevant resources ready to share

      *Generated by AI Brief System (stub mode)*
    BRIEF

    PreSessionBrief.create!(
      booking: booking,
      content: content,
      model_used: "stub",
      prompt_tokens: 0,
      completion_tokens: 0,
      total_tokens: 0,
      status: "generated"
    )

    Rails.logger.info("[AI] Stub brief generated for booking=#{booking.id}")
  end

  def generate_with_llm(booking)
    # Future: implement LlmClient integration
    # result = LlmClient.generate_brief(member: booking.member, mentor: booking.slot.mentor)
    # PreSessionBrief.create!(booking: booking, content: result[:content], ...)
    generate_stub_brief(booking)
  end
end
